language: python

python:
  - "2.7"
  - "3.5"

sudo: true
env: DISPLAY=':99.0'
dist: trusty
addons: # get google-chrome-stable
  chrome: stable

before_script:
  - wget -N http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - unzip ~/chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.14/bin/
  - unzip ~/chromedriver_linux64.zip -d /home/travis/virtualenv/python3.5.5/bin/
  - rm ~/chromedriver_linux64.zip
  - export CHROME_BIN=chromium-browser
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install: "pip install -r requirements.txt"

script:
  - python google_scraper.py "https://www.google.com/search?q=cats&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiwoLXK1qLVAhWqwFQKHYMwBs8Q_AUICigB"

notifications:
  email: false
